# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/SDUP_Zdalne/Huffman_Part2/Huffman_2.srcs/sources_1/bd/Huffman_On_Ip/ip/Huffman_On_Ip_xbar_0_1/Huffman_On_Ip_xbar_0.xci
# IP: The module: 'Huffman_On_Ip_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SDUP_Zdalne/Huffman_Part2/Huffman_2.srcs/sources_1/bd/Huffman_On_Ip/ip/Huffman_On_Ip_xbar_0_1/Huffman_On_Ip_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Huffman_On_Ip_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/SDUP_Zdalne/Huffman_Part2/Huffman_2.srcs/sources_1/bd/Huffman_On_Ip/ip/Huffman_On_Ip_xbar_0_1/Huffman_On_Ip_xbar_0.xci
# IP: The module: 'Huffman_On_Ip_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SDUP_Zdalne/Huffman_Part2/Huffman_2.srcs/sources_1/bd/Huffman_On_Ip/ip/Huffman_On_Ip_xbar_0_1/Huffman_On_Ip_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Huffman_On_Ip_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
